apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: xenon
spec:
  selector:
    matchLabels:
      app: xenon
  serviceName: "xenon"
  replicas: 4
  template:
    metadata:
      labels:
        app: xenon
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: xenon
        image: alpine:3.8
        command: ["/bin/sh","-c"]
        args: ["echo shard ${HOSTNAME##*-}; sleep 3000"]
        resources:
          requests:
            memory: 512Mi
          limits:
            memory: 1Gi