version: '3'
services:
  xenon:
    build: .
    restart: unless-stopped
    env_file:
     - xenon.env
    depends_on:
      - "rethinkdb"
  rethinkdb:
    image: "rethinkdb:2.3.6"
    restart: unless-stopped
    expose:
     - "28015"